project:
  type: book

book:
  title: "Learn Visual Computing"
  author: "Yuhao Zhu"
  date: "7/12/2025"

  chapters:
    - index.qmd
    - intro.qmd
    - part: hvs.qmd
      chapters:
        - hvs-intro.qmd
        - hvs-receptor.qmd
        - hvs-adaptation.qmd
    - summary.qmd
    - references.qmd

number-depth: 3

bibliography: refs.bib
csl: chicago-author-date.csl

format:
  html:
    theme:
      - cosmo
      - brand
    default-image-extension: svg
    toc: true
    toc-location: right
    #toc-scroll: true
    number-sections: true
    anchor-sections: true
  pdf:
    documentclass: scrreprt
    default-image-extension: pdf

editor: source