project:
  type: book

book:
  title: "Foundations of Visual Computing"
  author: "Yuhao Zhu"
  date: "7/12/2025"

  #cover-image: cover.png

  chapters:
    - index.qmd
    - intro.qmd
    - part: hvs.qmd
      chapters:
        - hvs-intro.qmd
        - hvs-receptor.qmd
        - hvs-color.qmd
        - hvs-colorimetry.qmd
        - hvs-retcomp.qmd
        - hvs-adaptation.qmd
    - part: rendering.qmd
      chapters:
        - rendering-basics.qmd
        - rendering-surface.qmd
        - rendering-sss.qmd
    - part: imaging.qmd
      chapters:
        - imaging-optics.qmd
        - imaging-sensor.qmd
        - imaging-noises.qmd
        - imaging-isp.qmd
    - part: display.qmd
      chapters:
        - display-basics.qmd
        - display-impl.qmd
    #- summary.qmd
    - references.qmd

number-depth: 3

bibliography: refs.bib
csl: chicago-author-date.csl

format:
  html:
    theme:
      - cosmo
      - brand
    default-image-extension: svg
    # include-in-header:
    #   - mathjax.html
    # toc: true
    # toc-location: right
    # toc-scroll: true
    # number-sections: true
    # anchor-sections: true
  pdf:
    documentclass: scrreprt
    default-image-extension: pdf

editor: source