# Surface Scattering {#sec-chpt-mat-ss}

When a group of photons arrives at a material surface, some of the photons might be immediately turned away (i.e., reflected) while others might penetrate into the material (i.e., refracted).
The refracted portion is scattered further inside the material, giving rise to subsurface scattering, which we will discuss in the next chapter.
This chapter is concerned with surface scattering --- the apparent reflection at the surface.
There are two properties we care about in surface scattering: the directions of the reflection and the energy along each direction.
These two properties are captured by what is known as the BRDF, which is the protagonist of this chapter.
We will then derive a few very useful equations and properties based on BRDF.

::: {.hidden}
$$
\def\oi{{\omega_i}}
\def\os{{\omega_s}}
\def\Oi{{\Omega_i}}
\def\Os{{\Omega_s}}
\def\d{{\text{d}}}
\def\D{{\Delta}}
\def\do{{\d\omega}}
\def\Do{{\Delta\omega}}
\def\doi{{\d\omega_i}}
\def\dos{{\d\omega_s}}
\def\Doi{{\D\omega_i}}
\def\Dos{{\D\omega_s}}
\def\H{{\mathbf{H}}}
\newcommand{\cM}{\mathcal{M}}
\newcommand{\cL}{\mathcal{L}}
$$
:::

## BRDF {#sec-chpt-mat-ss-brdf}

Generally, the energy distribution of the surface scattering is captured by the Bidirectional Reflectance Distribution Function (**BRDF**) [@nicodemus1977geometrical].
Informally, it tells us how the incident energy from a particular direction is distributed to different exiting directions.
The BRDF is parameterized by three parameters: a surface point $p$, the direction of light incident on $p$, denoted $\oi$, and the direction of light leaving $p$, denoted $\os$.
So the BRDF is usually written as $f_r(p, \os, \oi)$.

The way to understand BRDF $f_r(p, \os, \oi)$ is to consider  the following.
$L(p, \os)$, i.e., the radiance leaving $p$ toward $\os$, is dependent on the light incident on $p$.
When the incident light on $p$ comes from only the direction $\oi$, the irradiance at $p$ is zero, since the solid angle of a single direction $\oi$ is zero, so naturally $L(p, \os)$ is 0 (assuming there is no other light hitting $p$).
When $p$ receives light from a non-zero solid angle of directions $\Delta\oi$ (centered around $\oi$), the irradiance of $p$ is increased by $\Delta E(p, \oi)$.
At the same time, due to this increase in incident light, $L(p, \os)$ is no longer zero; the increase in the radiance leaving $p$ over $\os$ is denoted $\Delta L(p, \os)$.

As we increase $\Delta \oi$, both $\Delta E(p, \oi)$ and $\Delta L(p, \os)$ increase.
BRDF is defined as the ratio of the two *increments* when $\Delta \oi$ approaches 0 (when the radiance along all directions in $\Delta \oi$ can be thought of as a constant):

$$
\begin{align}
    f_r(p, \os, \oi) = \lim_{\Delta \oi \rightarrow 0}\frac{\Delta L(p, \os)}{\Delta E(p, \oi)} = \frac{\text{d}L(p, \os)}{\text{d}E(p, \oi)} = \frac{\text{d}L(p, \os)}{L(p, \oi)\cos\theta_i \text{d}\oi}.
\end{align}
$$ {#eq-brdf}

### A Useful Approximation

Now assume that we illuminate $p$ through a finite, but small, solid angle $\Oi$.
Turning the differential equation into an integral equation, we get:

$$
\begin{align}
    L(p, \os) = \int^{\Oi} f_r(p, \os, \oi) \text{d}E(p, \oi).
\end{align}
$$ {#eq-brdf_finite_1}

Using the definition of radiance in @eq-radiance_3, we get:
$$
\begin{align}
    L(p, \os) = \int^{\Oi} f_r(p, \os, \oi) L(p, \oi)\cos\theta_i \text{d}\oi.
\end{align}
$$ {#eq-brdf_finite_2}

If we assume that the BRDF is a constant over all the directions in $\Oi$, @eq-brdf_finite_2 is simplified to:

$$
\begin{align}
    L(p, \os) \approx f_r(p, \os, \oi) \int^{\Oi} L(p, \oi)\cos\theta_i \text{d}\oi.
\end{align}
$$ {#eq-brdf_finite_3}

The integration in @eq-brdf_finite_3 has no analytical solution, since we do not know the analytical form of $L(p, \oi)$, but we know the integration is just another way of expressing the total irradiance incident upon $p$ over $\Oi$, which is denoted as $E(p, \Oi)$^[To be more rigorous, the integration in @eq-brdf_finite_3 evaluates to $E(p, \Oi) + C$, where $C$ is a constant.
Given the boundary condition that $L(p, \os) = 0$ when $E(p, \Oi) = 0$, we know $C=0$, so $C$ is omitted.].
This gets us @eq-brdf_finite_4:

$$
\begin{align}
    L(p, \os) \approx f_r(p, \os, \oi) E(p, \Oi).
\end{align}
$$ {#eq-brdf_finite_4}

Thus, we can approximate the BRDF as:
$$
\begin{align}
    f_r(p, \os, \oi) &\approx \frac{L(p, \os)}{E(p, \Oi)}.
\end{align}
$$ {#eq-brdf_finite_5}

Ultimately, we can see from @eq-brdf_finite_5 that the BRDF $f_r(p, \os, \oi)$ can also be calculated as the ratio between the *absolute* radiance $L(p, \oi)$ and the absolute irradiance $E(p, \Oi)$ illuminated from a very small, but finite solid angle $\Oi$.
Another way to interpret this is that the so-calculated BRDF is the average BRDF over $\Oi$.
This derivation is useful for actually measuring a BRDF, which we will discuss in @sec-chpt-mat-rt-brdf, where we will have no choice but to use a non-zero solid angle for illumination, because physically we just cannot illuminate a point through an infinitesimal solid angle $\doi$.

### Isotropic Material

A 3D direction $\omega$ expressed in the Cartesian coordinate system can also be expressed by two 2D planar angles in the spherical coordinate system: the polar angle $\theta$ and the azimuthal angle $\phi$.
So BRDF can also be parameterized as $f_r(p, \theta_s, \phi_s, \theta_i, \phi_i)$.
A material is **isotropic** if its BRDF satisfies $f_r(p, \theta_s, \phi_s, \theta_i, \phi_i) = f_r(p, \theta_s, \phi_s+x, \theta_i, \phi_i+x)$ for any $x$.
An intuitive way to think of an isotropic material is this: if you pick a point $p$ and rotate the material about the normal vector at $p$, the color of $p$ does not change.
This is because rotation about the normal vector keeps $\theta_i$ and $\theta_s$ unchanged and varies $\phi_i$ and $\phi_s$ by the same amount.

The nice thing about an isotropic BRDF is it can be parameterized with one fewer degree of freedom: $f_r(p, \theta_s, \phi_s - \phi_i, \theta_i)$.
This is because it is $(\phi_i - \phi_s)$ rather than the specific values of $\phi_s$ or $\phi_i$ that matter.

## Reflectance and Albedo {#sec-chpt-mat-ss-reflectance}

The BRDF does not have to be a value between 0 and 1.
Let's say that there is 100 J of energy incident on a point coming from a solid angle $\Delta \oi$.
That amount of energy is distributed across all the outgoing directions in the hemisphere, which forms a solid angle of $4\pi/2 = 2\pi$.
So on average the energy exiting per direction is $\frac{100}{2\pi}J$, which clearly is greater than 1.
This is not surprising, since BRDF is ultimately a *density* measure, a *distribution*, which is most meaningful when it is integrated to calculate some quantity.
Integrating the BRDF gives a percentage/fraction measure between 0 and 1, i.e., reflectance, which we will discuss next.

### Directional-Hemispherical Reflectance {#sec-chpt-mat-ss-reflectance-dhr}

For the energy to be conserved, the total outgoing energy at any point must not exceed that of the incident energy received by that point.
Assume that a point $p$ receives an irradiance $\d E_i$ from a direction $\oi$ over an infinitesimal solid angle $\doi$, and the outgoing radiance along the direction $\os$ due to that irradiance is $f_r(p, \os, \oi)\d E_i$.
Then the outgoing irradiance leaving $p$ over an infinitesimal solid angle $\dos$ around $\os$ would be $f_r(p, \os, \oi)\d E_i\cos\theta_s\dos$.
If we integrate all the outgoing directions, we get the total outgoing irradiance $\d E_o$, which must not exceed the incident irradiance $\d E_i$:

$$
\begin{align}
    \d E_o = \int^{\Omega} \d E_i f_r(p, \os, \oi) \cos\theta_s\text{d}\os.
\end{align}
$$ {#eq-energy_con_0}

$\d E_i$ is independent of $\os$, so it can be hoisted out of the integration.
Therefore, we have the following equation, which holds for any arbitrary incident direction $\oi$:

$$
\begin{align}
    \int^{\Omega}f_r(p, \os, \oi)\cos\theta_s\text{d}\os = \frac{\d E_o}{\d E_i} = \rho_{dh}(p, \oi) \leq 1.
\end{align}
$$ {#eq-energy_con_1}

$\rho_{dh}$ is defined as the ratio between $\d E_o$ and $\d E_i$.
When $\Omega$ is the hemisphere, $\rho_{dh}$ is called the **directional-hemispherical reflectance** in the computer vision and graphics literature, and is interpreted as the percentage of energy scattered by a point over the entire hemisphere given the incident light from a particular direction.
Clearly, $\rho_{dh}$ is a function of both $p$ and $\oi$ and takes a value between 0 and 1.

### Hemispherical-Directional Reflectance {#sec-chpt-mat-ss-reflectance-hdr}

Since we are dealing with geometric optics, the Helmholtz reciprocity holds:

$$
\begin{align}
    f_r(p, \os, \oi) = f_r(p, \oi, \os),
\end{align}
$$

which means the energy conservation can also be expressed as:

$$
\begin{align}
    \int^{\Omega}f_r(p, \os, \oi)\cos\theta_i\text{d}\oi = \rho_{hd}(p, \os) \leq 1,
\end{align}
$$ {#eq-energy_con_2}

where $\rho_{hd}$ is called the **hemispherical-directional reflectance** when $\Omega$ is the hemisphere.
$\rho_{hd}$, a function of $p$ and $\os$, is interpreted as the percentage of energy reflected toward a particular direction $\os$ given the incident energy over the entire hemisphere.

@eq-energy_con_2 can be derived by first rewriting @eq-energy_con_1 as $\int^{\Omega}f_r(p, \oi, \os)\cos\theta_s\text{d}\os \leq 1$ (using the reciprocity) followed by switching $\os$ and $\oi$ (simply a change of notation).
This derivation suggests that $\rho_{hd}(p, \oi) = \rho_{dh}(p, \os)$, a natural consequence of the reciprocity\footnote{For instance, if $\rho_{hd}(p, \oi) = \frac{1}{1+\oi^2}$, then $\rho_{dh}(p, \os)$ must take the form $\rho_{dh}(p, \os) = \frac{1}{1+\os^2}$}.

### Hemispherical-Hemispherical Reflectance {#sec-chpt-mat-ss-reflectance-hhr}

We can also describe the relationship between all the outgoing irradiance $E_o$ of a point over a solid angle $\Os$ due to all the incident irradiance $E_i$ over a solid angle $\Oi$:

$$
\begin{align}
    E_o &= \int^{\Omega_s} \Big(\int^{\Omega_i} f_r(p, \os, \oi) L(p, \oi) \cos\theta_i\text{d}\oi\Big) \cos\theta_s \dos, \\
    E_i &= \int^{\Omega_i} L(p, \oi) \cos\theta_i\text{d}\oi
\end{align}
$$ {#eq-albedo_0}

Due to energy conservation, we have:

$$
\begin{align}
    \rho_{hh}(p) = \frac{E_o}{E_i} \leq 1.
\end{align}
$$ {#eq-albedo_1}

@eq-albedo_1 defines $\rho_{hh}$, which is called the **hemispherical-hemispherical reflectance** when both $\Omega_i$ and $\Omega_s$ are hemispheres.
$\rho_{hh}$ has another name: **albedo**.

When $f_r(p, \os, \oi)$ is independent of (invariant to) $\oi$ and $\os$, i.e., when $p$ is an ideal **Lambertian** surface (see @sec-chpt-mat-basics-radiometry-lamb and @sec-chpt-mat-ss-mat), @eq-albedo_0 can be re-written as:

$$
\begin{align}
    E_o = E_i \rho_{hh}(p) = & \int^{\Omega_s} f_r(p, \os, \oi) (\int^{\Omega_i} L(p, \oi) \cos\theta_i\text{d}\oi) \cos\theta_s \dos \label{eq:lamb_0} \\
    = & \int^{\Omega_s} f_r(p, \os, \oi) E_i \cos\theta_s \dos \label{eq:lamb_1} \\
    = & E_i  \int^{\Omega_s} f_r(p, \os, \oi) \cos\theta_s \dos \label{eq:lamb_2} \\
    = & E_i \rho_{dh}(p, \oi) \label{eq:lamb_3},
\end{align}
$$

where \Eqn{eq:lamb_1} is derived using the definition of $E_i$ in \Eqn{eq:albedo_0}, \Eqn{eq:lamb_2} is derived since $E_i$ is independent of $\os$, and \Eqn{eq:lamb_3} is derived by using the definition of $\rho_{dh}$ in \Eqn{eq:energy_con_1}.
